---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this tasks , i want install apache2 webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family== "Debian" 
  - name: in this tasks, i want to start webserver on ubuntu 
    service:
      name: apache2
      state: started
    when: ansible_os_family== "Debian" 
  - name:   in this tasts, i want to install httpd webserver on RedHat
    dnf:
      name: httpd
      state: present
    when: ansible_os_family== "RedHat"
  - name: in this tasts, i want to webserver on RedHat
    service:
       name: httpd
       state: started
    when: ansible_os_family== "RedHat"