---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: in this tasks , i want install apache2 webserver
    apt:
     name: "{{mywebpackonubuntu}}"
     state: present
    when: ansible_os_family== "Debian" 
  - name: in this tasks, i want to start webserver on ubuntu 
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian" 
  - name:   in this tasts, i want to install httpd webserver on RedHat
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family== "RedHat"
  - name: in this tasts, i want to webserver on RedHat
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family== "RedHat"