---
- hosts: all
  become: yes
  gather_fact: yes
  tasks:
  - name: in this tasks , i want install apache2 webserver
    apt:
     name: apache2
     state: present
  - name: in this tasks, i want to start webserver
    service:
      name: apache2
      state: started